export const infiniteScrollTestData = [
  [
    {
      id: 1,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 2,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 3,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 1,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 2,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 3,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 1,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 2,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 3,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 1,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 2,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 3,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],
  [
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],
  [
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],[
    {
      id: 4,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 5,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
    {
      id: 6,
      title: "Table tennis",
      challenger: "@Qubigs",
      isOnline: true,
      challengerImg: require("../assets/images/profile-img.png"),
      stake: "50",
      timeStamp: "1 min ago",
      group: true,
    },
  ],
];

export const fetchTestData = (page:number) =>{
    if(infiniteScrollTestData.length > page ){
      return infiniteScrollTestData[page]
    }
    else{
      return null;
    }
}